CREATE USER uimp1 IDENTIFIED BY uimp1 
DEFAULT TABLESPACE users QUOTA 5M ON users;

GRANT CREATE SESSION, CREATE TABLE TO uimp1;

CREATE USER uimp1 IDENTIFIED BY uimp1 
DEFAULT TABLESPACE users QUOTA 5M ON users;

GRANT CREATE SESSION, CREATE TABLE TO uimp1;


CREATE USER uimp1 IDENTIFIED BY uimp1 
DEFAULT TABLESPACE users QUOTA 5M ON users;

GRANT CREATE SESSION, CREATE TABLE TO uimp1;


CREATE USER uimp1 IDENTIFIED BY uimp1 
DEFAULT TABLESPACE users QUOTA 5M ON users;

GRANT CREATE SESSION, CREATE TABLE TO uimp1;


CREATE USER uimp2 IDENTIFIED BY uimp2
DEFAULT TABLESPACE users QUOTA 5M ON users;

GRANT CREATE SESSION, CREATE TABLE TO uimp2;

CREATE USER uimp3 IDENTIFIED BY uimp3
DEFAULT TABLESPACE users QUOTA 5M ON users;

GRANT CREATE SESSION, CREATE TABLE TO uimp3;

-- Unlock account & change password
ALTER USER hr ACCOUNT UNLOCK;
ALTER USER hr IDENTIFIED BY hr;
